{% set version = "0.14.1" %}

package:
  name: ycm-cmake-modules
  version: {{ version }}

source:
  url: https://github.com/robotology/ycm/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 81280620725e5d70e07079ba0a71e249223e39e14683314631249784bd006e5f

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - ninja

test:
  commands:
    - test -f ${PREFIX}/share/cmake/YCM/YCMConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\share\\cmake\\YCM\\YCMConfig.cmake exit 1  # [win]

about:
  home: https://github.com/robotology/ycm
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Extra CMake Modules for YARP and friends.

extra:
  recipe-maintainers:
    - traversaro
